service: tinderCloneBE
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  app:
    handler: start.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    timeout: 20
plugins:
  - serverless-offline
  - serverless-ngrok-tunnel

custom:
  serverless-offline:
    httpPort: 4000
  ngrokTunnel:
    tunnels:
      - port: 4000
